/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "stm32f429i_discovery_lcd.h"
#include "stm32f4xx_hal_rtc.h"
#include "main.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x09)
#define ID_SPINBOX_0 (GUI_ID_USER + 0x0A)
#define ID_DROPDOWN_0 (GUI_ID_USER + 0x0B)
#define ID_SPINBOX_1 (GUI_ID_USER + 0x0C)
#define ID_SPINBOX_2 (GUI_ID_USER + 0x0E)
#define ID_SPINBOX_3 (GUI_ID_USER + 0x0F)
#define ID_SPINBOX_4 (GUI_ID_USER + 0x10)
#define ID_BUTTON_0 (GUI_ID_USER + 0x11)
#define ID_BUTTON_1 (GUI_ID_USER + 0x12)
#define ID_TEXT_0 (GUI_ID_USER + 0x13)
#define ID_TEXT_1 (GUI_ID_USER + 0x14)
#define ID_TEXT_2 (GUI_ID_USER + 0x15)
#define ID_TEXT_3 (GUI_ID_USER + 0x16)
#define ID_TEXT_4 (GUI_ID_USER + 0x17)
#define ID_TEXT_5 (GUI_ID_USER + 0x18)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
WM_HWIN hDTWin;
WM_HWIN hYearSpin;
WM_HWIN hMonthDrop;
WM_HWIN hDaySpin;
WM_HWIN hHourSpin;
WM_HWIN hMinSpin;
WM_HWIN hSecSpin;


extern RTC_TimeTypeDef sTime;
extern RTC_DateTypeDef sDate;
extern RTC_HandleTypeDef hrtc;
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "DTFramewin", ID_FRAMEWIN_0, 0, 0, 240, 320, 0, 0x64, 0 },
  { SPINBOX_CreateIndirect, "YearSpinbox", ID_SPINBOX_0, 90, 13, 110, 35, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "MonthDropdown", ID_DROPDOWN_0, 90, 62, 110, 25, 0, 0x0, 0 },
  { SPINBOX_CreateIndirect, "DaySpinbox", ID_SPINBOX_1, 90, 100, 110, 35, 0, 0x0, 0 },
  { SPINBOX_CreateIndirect, "HourSpinbox", ID_SPINBOX_2, 15, 175, 60, 35, 0, 0x0, 0 },
  { SPINBOX_CreateIndirect, "MinSpinbox", ID_SPINBOX_3, 85, 175, 60, 35, 0, 0x0, 0 },
  { SPINBOX_CreateIndirect, "SecSpinbox", ID_SPINBOX_4, 155, 175, 60, 35, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "OKButton", ID_BUTTON_0, 120, 240, 95, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "CancelButton", ID_BUTTON_1, 15, 240, 95, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 20, 20, 60, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_1, 20, 65, 60, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_2, 20, 105, 60, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_3, 25, 150, 42, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_4, 100, 150, 33, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_5, 170, 150, 34, 20, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'DTFramewin'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetText(hItem, "Date & time");
    FRAMEWIN_SetFont(hItem, GUI_FONT_20_ASCII);
    //
    // Initialization of 'YearSpinbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_0);
    SPINBOX_SetFont(hItem, GUI_FONT_20_ASCII);
    //
    // Initialization of 'MonthDropdown'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0);
    DROPDOWN_AddString(hItem, "January");
    DROPDOWN_AddString(hItem, "February");
    DROPDOWN_AddString(hItem, "March");
    DROPDOWN_AddString(hItem, "April");
    DROPDOWN_AddString(hItem, "May");
    DROPDOWN_AddString(hItem, "June");
    DROPDOWN_AddString(hItem, "July");
    DROPDOWN_AddString(hItem, "August");
    DROPDOWN_AddString(hItem, "September");
    DROPDOWN_AddString(hItem, "October");
    DROPDOWN_AddString(hItem, "November");
    DROPDOWN_AddString(hItem, "December");
    DROPDOWN_SetFont(hItem, GUI_FONT_20_ASCII);
    //
    // Initialization of 'DaySpinbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_1);
    SPINBOX_SetFont(hItem, GUI_FONT_20_ASCII);
    //
    // Initialization of 'Spinbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_2);
    SPINBOX_SetFont(hItem, GUI_FONT_20_ASCII);
    //
    // Initialization of 'Spinbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_3);
    SPINBOX_SetFont(hItem, GUI_FONT_20_ASCII);
    //
    // Initialization of 'Spinbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_4);
    SPINBOX_SetFont(hItem, GUI_FONT_20_ASCII);
    //
    // Initialization of 'OKButton'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, GUI_FONT_20_ASCII);
    BUTTON_SetText(hItem, "OK");
    //
    // Initialization of 'CancelButton'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, GUI_FONT_20_ASCII);
    BUTTON_SetText(hItem, "Cancel");
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetText(hItem, "Year");
    TEXT_SetFont(hItem, GUI_FONT_20_ASCII);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, GUI_FONT_20_ASCII);
    TEXT_SetText(hItem, "Month");
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, GUI_FONT_20_ASCII);
    TEXT_SetText(hItem, "Day");
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, GUI_FONT_20_ASCII);
    TEXT_SetText(hItem, "Hour");
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetFont(hItem, GUI_FONT_20_ASCII);
    TEXT_SetText(hItem, "Min");
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetFont(hItem, GUI_FONT_20_ASCII);
    TEXT_SetText(hItem, "Sec");
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_SPINBOX_0: // Notifications sent by 'YearSpinbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_0: // Notifications sent by 'MonthDropdown'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
		  {
			  uint8_t month = DROPDOWN_GetSel(hMonthDrop) + 1;
			  uint8_t day = SPINBOX_GetValue(hDaySpin);
				if(month == 2) {
					SPINBOX_SetRange(hDaySpin, 1, 28);
					if( day > 28 ) {
						SPINBOX_SetValue(hDaySpin, 28);
					}
				} else if( month == 4 || month == 6 || month == 9 || month == 11) {
					SPINBOX_SetRange(hDaySpin, 1, 30);
					if( day > 30 ) {
						SPINBOX_SetValue(hDaySpin, 30);
					}
				} else {
					SPINBOX_SetRange(hDaySpin, 1, 31);
				}
		  }
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SPINBOX_1: // Notifications sent by 'DaySpinbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SPINBOX_2: // Notifications sent by 'Spinbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SPINBOX_3: // Notifications sent by 'Spinbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SPINBOX_4: // Notifications sent by 'Spinbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'OKButton'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
    	  sDate.Year = SPINBOX_GetValue(hYearSpin) - 2000;
    	  sDate.Month = DROPDOWN_GetSel(hMonthDrop) + 1;
    	  sDate.Date = SPINBOX_GetValue(hDaySpin);
    	  sTime.Hours = SPINBOX_GetValue(hHourSpin);
    	  sTime.Minutes = SPINBOX_GetValue(hMinSpin);
    	  sTime.Seconds = SPINBOX_GetValue(hSecSpin);
    	  events |= EVT_DATE_TIME_SETUP;
    	  events &= ~EVT_DATE_TIME_DLG;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'CancelButton'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
    	  events &= ~EVT_DATE_TIME_DLG;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateDTFramewin
*/
WM_HWIN CreateDTFramewin(void);
WM_HWIN CreateDTFramewin(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)


void CreateDTDialog(void) {
	hDTWin = CreateDTFramewin();
	hYearSpin = WM_GetDialogItem(hDTWin, ID_SPINBOX_0);
	hMonthDrop = WM_GetDialogItem(hDTWin, ID_DROPDOWN_0);
	hDaySpin = WM_GetDialogItem(hDTWin, ID_SPINBOX_1);
	hHourSpin = WM_GetDialogItem(hDTWin, ID_SPINBOX_2);
	hMinSpin = WM_GetDialogItem(hDTWin, ID_SPINBOX_3);
	hSecSpin = WM_GetDialogItem(hDTWin, ID_SPINBOX_4);

	FRAMEWIN_SetClientColor(hDTWin,LCD_COLOR_LIGHTGRAY);

	HAL_RTC_GetTime(&hrtc, &sTime, RTC_FORMAT_BIN);
	HAL_RTC_GetDate(&hrtc, &sDate, RTC_FORMAT_BIN);

	SPINBOX_SetRange(hYearSpin, 2000, 2099);
	SPINBOX_SetValue(hYearSpin, (I32)sDate.Year+2000);

	DROPDOWN_SetSel(hMonthDrop, sDate.Month-1);
	DROPDOWN_SetListHeight(hMonthDrop, 130);
	DROPDOWN_SetAutoScroll(hMonthDrop, 1);
	DROPDOWN_SetScrollbarWidth(hMonthDrop, 20);

	if(sDate.Month == 2) {
		SPINBOX_SetRange(hDaySpin, 1, 28);
	} else if( sDate.Month == 4 || sDate.Month == 6 || sDate.Month == 9 || sDate.Month == 11) {
		SPINBOX_SetRange(hDaySpin, 1, 30);
	} else {
		SPINBOX_SetRange(hDaySpin, 1, 31);
	}
	SPINBOX_SetValue(hDaySpin, sDate.Date);

	SPINBOX_SetRange(hHourSpin, 0, 23);
	SPINBOX_SetValue(hHourSpin, sTime.Hours);

	SPINBOX_SetRange(hMinSpin, 0, 59);
	SPINBOX_SetValue(hMinSpin, sTime.Minutes);

	SPINBOX_SetRange(hSecSpin, 0, 59);
	SPINBOX_SetValue(hSecSpin, sTime.Seconds);
}

void DTDialogProcess(void) {
	//GUI_Delay(100); // for multitasking
	GUI_Exec();
	WM_PaintWindowAndDescs(hDTWin);
}

void DTDialogClose(void) {
	GUI_EndDialog(hDTWin,0);
}
// USER END

/*************************** End of file ****************************/
